### ISSUE TITLE
example throws error

### ISSUE THREAD

**Issue by madsurgeon** [gliwka/bittrex-market#29]
Hi,

When running your example I am getting the following error:

```
/home/david/node_modules/bittrex-market/lib/manager.js:12
class MarketManager extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/david/node_modules/bittrex-market/index.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Running on node.js version 4.2.6 on ubuntu.

Thanks,
David

**Comment by madsurgeon** [comment]
Hi Matthias,

Thank you for your input.
Now with node.js 8.9.3 it works.
However, FYI, there seems to be an error in your example: 

```
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503
/home/david/node_modules/bittrex-market/example.js:30
            bitcoin.on(`orderbook.diff.${side}.${type}`, (event) => {
            ^

ReferenceError: bitcoin is not defined
    at eventTypes.forEach (/home/david/node_modules/bittrex-market/example.js:30:13)
    at Array.forEach (<anonymous>)
    at sides.forEach (/home/david/node_modules/bittrex-market/example.js:29:20)
    at Array.forEach (<anonymous>)
    at marketManager.market (/home/david/node_modules/bittrex-market/example.js:28:11)
    at client.call.done (/home/david/node_modules/bittrex-market/lib/manager.js:162:32)
    at callCallbacks.(anonymous function) (/home/david/node_modules/signalr-client/signalR.js:429:6)
    at handleCallResult (/home/david/node_modules/signalr-client/signalR.js:436:11)
    at WebSocketConnection.<anonymous> (/home/david/node_modules/signalr-client/signalR.js:748:7)
    at emitOne (events.js:116:13)

```

I guess line 30 should read ethereum.on instead of bitcoin.on.
When I run this slightly changed version, it works. However, I am still getting first the lines:

```
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503

```

From there on it looks ok.

Thanks a lot for releasing this code!

Kind regards,
David

**Comment by madsurgeon** [comment]
Hi Matthias,

Thank you for your input.
Now with node.js 8.9.3 it works.
However, FYI, there seems to be an error in your example: 

```
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503
/home/david/node_modules/bittrex-market/example.js:30
            bitcoin.on(`orderbook.diff.${side}.${type}`, (event) => {
            ^

ReferenceError: bitcoin is not defined
    at eventTypes.forEach (/home/david/node_modules/bittrex-market/example.js:30:13)
    at Array.forEach (<anonymous>)
    at sides.forEach (/home/david/node_modules/bittrex-market/example.js:29:20)
    at Array.forEach (<anonymous>)
    at marketManager.market (/home/david/node_modules/bittrex-market/example.js:28:11)
    at client.call.done (/home/david/node_modules/bittrex-market/lib/manager.js:162:32)
    at callCallbacks.(anonymous function) (/home/david/node_modules/signalr-client/signalR.js:429:6)
    at handleCallResult (/home/david/node_modules/signalr-client/signalR.js:436:11)
    at WebSocketConnection.<anonymous> (/home/david/node_modules/signalr-client/signalR.js:748:7)
    at emitOne (events.js:116:13)

```

I guess line 30 should read ethereum.on instead of bitcoin.on.
When I run this slightly changed version, it works. However, I am still getting first the lines:

```
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503

```

From there on it looks ok.

Thanks a lot for releasing this code!

Kind regards,
David
